spring:
  application:
    name: Hotel-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: prafull
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 4501

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:4600/eureka
